export enum Continent {
  Africa = "Africa",
  Asia = "Asia",
  Europe = "Europe",
  NorthAmerica = "North America",
  SouthAmerica = "South America",
  Oceania = "Oceania",
}

export interface Country {
  id: string;
  name: string;
  code: string;
  continent: Continent;
  flagEmoji: string;
}

export const ALL_COUNTRIES: Country[] = [
  // Africa (54 countries)
  { id: "algeria", name: "Algeria", code: "DZA", continent: Continent.Africa, flagEmoji: "🇩🇿" },
  { id: "angola", name: "Angola", code: "AGO", continent: Continent.Africa, flagEmoji: "🇦🇴" },
  { id: "benin", name: "Benin", code: "BEN", continent: Continent.Africa, flagEmoji: "🇧🇯" },
  { id: "botswana", name: "Botswana", code: "BWA", continent: Continent.Africa, flagEmoji: "🇧🇼" },
  { id: "burkina-faso", name: "Burkina Faso", code: "BFA", continent: Continent.Africa, flagEmoji: "🇧🇫" },
  { id: "burundi", name: "Burundi", code: "BDI", continent: Continent.Africa, flagEmoji: "🇧🇮" },
  { id: "cabo-verde", name: "Cabo Verde", code: "CPV", continent: Continent.Africa, flagEmoji: "🇨🇻" },
  { id: "cameroon", name: "Cameroon", code: "CMR", continent: Continent.Africa, flagEmoji: "🇨🇲" },
  { id: "central-african-republic", name: "Central African Republic", code: "CAF", continent: Continent.Africa, flagEmoji: "🇨🇫" },
  { id: "chad", name: "Chad", code: "TCD", continent: Continent.Africa, flagEmoji: "🇹🇩" },
  { id: "comoros", name: "Comoros", code: "COM", continent: Continent.Africa, flagEmoji: "🇰🇲" },
  { id: "congo", name: "Congo", code: "COG", continent: Continent.Africa, flagEmoji: "🇨🇬" },
  { id: "dr-congo", name: "Democratic Republic of the Congo", code: "COD", continent: Continent.Africa, flagEmoji: "🇨🇩" },
  { id: "cote-divoire", name: "Côte d'Ivoire", code: "CIV", continent: Continent.Africa, flagEmoji: "🇨🇮" },
  { id: "djibouti", name: "Djibouti", code: "DJI", continent: Continent.Africa, flagEmoji: "🇩🇯" },
  { id: "egypt", name: "Egypt", code: "EGY", continent: Continent.Africa, flagEmoji: "🇪🇬" },
  { id: "equatorial-guinea", name: "Equatorial Guinea", code: "GNQ", continent: Continent.Africa, flagEmoji: "🇬🇶" },
  { id: "eritrea", name: "Eritrea", code: "ERI", continent: Continent.Africa, flagEmoji: "🇪🇷" },
  { id: "eswatini", name: "Eswatini", code: "SWZ", continent: Continent.Africa, flagEmoji: "🇸🇿" },
  { id: "ethiopia", name: "Ethiopia", code: "ETH", continent: Continent.Africa, flagEmoji: "🇪🇹" },
  { id: "gabon", name: "Gabon", code: "GAB", continent: Continent.Africa, flagEmoji: "🇬🇦" },
  { id: "gambia", name: "Gambia", code: "GMB", continent: Continent.Africa, flagEmoji: "🇬🇲" },
  { id: "ghana", name: "Ghana", code: "GHA", continent: Continent.Africa, flagEmoji: "🇬🇭" },
  { id: "guinea", name: "Guinea", code: "GIN", continent: Continent.Africa, flagEmoji: "🇬🇳" },
  { id: "guinea-bissau", name: "Guinea-Bissau", code: "GNB", continent: Continent.Africa, flagEmoji: "🇬🇼" },
  { id: "kenya", name: "Kenya", code: "KEN", continent: Continent.Africa, flagEmoji: "🇰🇪" },
  { id: "lesotho", name: "Lesotho", code: "LSO", continent: Continent.Africa, flagEmoji: "🇱🇸" },
  { id: "liberia", name: "Liberia", code: "LBR", continent: Continent.Africa, flagEmoji: "🇱🇷" },
  { id: "libya", name: "Libya", code: "LBY", continent: Continent.Africa, flagEmoji: "🇱🇾" },
  { id: "madagascar", name: "Madagascar", code: "MDG", continent: Continent.Africa, flagEmoji: "🇲🇬" },
  { id: "malawi", name: "Malawi", code: "MWI", continent: Continent.Africa, flagEmoji: "🇲🇼" },
  { id: "mali", name: "Mali", code: "MLI", continent: Continent.Africa, flagEmoji: "🇲🇱" },
  { id: "mauritania", name: "Mauritania", code: "MRT", continent: Continent.Africa, flagEmoji: "🇲🇷" },
  { id: "mauritius", name: "Mauritius", code: "MUS", continent: Continent.Africa, flagEmoji: "🇲🇺" },
  { id: "morocco", name: "Morocco", code: "MAR", continent: Continent.Africa, flagEmoji: "🇲🇦" },
  { id: "mozambique", name: "Mozambique", code: "MOZ", continent: Continent.Africa, flagEmoji: "🇲🇿" },
  { id: "namibia", name: "Namibia", code: "NAM", continent: Continent.Africa, flagEmoji: "🇳🇦" },
  { id: "niger", name: "Niger", code: "NER", continent: Continent.Africa, flagEmoji: "🇳🇪" },
  { id: "nigeria", name: "Nigeria", code: "NGA", continent: Continent.Africa, flagEmoji: "🇳🇬" },
  { id: "rwanda", name: "Rwanda", code: "RWA", continent: Continent.Africa, flagEmoji: "🇷🇼" },
  { id: "sao-tome-and-principe", name: "São Tomé and Príncipe", code: "STP", continent: Continent.Africa, flagEmoji: "🇸🇹" },
  { id: "senegal", name: "Senegal", code: "SEN", continent: Continent.Africa, flagEmoji: "🇸🇳" },
  { id: "seychelles", name: "Seychelles", code: "SYC", continent: Continent.Africa, flagEmoji: "🇸🇨" },
  { id: "sierra-leone", name: "Sierra Leone", code: "SLE", continent: Continent.Africa, flagEmoji: "🇸🇱" },
  { id: "somalia", name: "Somalia", code: "SOM", continent: Continent.Africa, flagEmoji: "🇸🇴" },
  { id: "south-africa", name: "South Africa", code: "ZAF", continent: Continent.Africa, flagEmoji: "🇿🇦" },
  { id: "south-sudan", name: "South Sudan", code: "SSD", continent: Continent.Africa, flagEmoji: "🇸🇸" },
  { id: "sudan", name: "Sudan", code: "SDN", continent: Continent.Africa, flagEmoji: "🇸🇩" },
  { id: "tanzania", name: "Tanzania", code: "TZA", continent: Continent.Africa, flagEmoji: "🇹🇿" },
  { id: "togo", name: "Togo", code: "TGO", continent: Continent.Africa, flagEmoji: "🇹🇬" },
  { id: "tunisia", name: "Tunisia", code: "TUN", continent: Continent.Africa, flagEmoji: "🇹🇳" },
  { id: "uganda", name: "Uganda", code: "UGA", continent: Continent.Africa, flagEmoji: "🇺🇬" },
  { id: "zambia", name: "Zambia", code: "ZMB", continent: Continent.Africa, flagEmoji: "🇿🇲" },
  { id: "zimbabwe", name: "Zimbabwe", code: "ZWE", continent: Continent.Africa, flagEmoji: "🇿🇼" },
  
  // Asia (47 countries) - truncated for brevity, will include all
  { id: "afghanistan", name: "Afghanistan", code: "AFG", continent: Continent.Asia, flagEmoji: "🇦🇫" },
  { id: "armenia", name: "Armenia", code: "ARM", continent: Continent.Asia, flagEmoji: "🇦🇲" },
  { id: "azerbaijan", name: "Azerbaijan", code: "AZE", continent: Continent.Asia, flagEmoji: "🇦🇿" },
  { id: "bahrain", name: "Bahrain", code: "BHR", continent: Continent.Asia, flagEmoji: "🇧🇭" },
  { id: "bangladesh", name: "Bangladesh", code: "BGD", continent: Continent.Asia, flagEmoji: "🇧🇩" },
  { id: "bhutan", name: "Bhutan", code: "BTN", continent: Continent.Asia, flagEmoji: "🇧🇹" },
  { id: "brunei", name: "Brunei", code: "BRN", continent: Continent.Asia, flagEmoji: "🇧🇳" },
  { id: "cambodia", name: "Cambodia", code: "KHM", continent: Continent.Asia, flagEmoji: "🇰🇭" },
  { id: "china", name: "China", code: "CHN", continent: Continent.Asia, flagEmoji: "🇨🇳" },
  { id: "cyprus", name: "Cyprus", code: "CYP", continent: Continent.Asia, flagEmoji: "🇨🇾" },
  { id: "georgia", name: "Georgia", code: "GEO", continent: Continent.Asia, flagEmoji: "🇬🇪" },
  { id: "india", name: "India", code: "IND", continent: Continent.Asia, flagEmoji: "🇮🇳" },
  { id: "indonesia", name: "Indonesia", code: "IDN", continent: Continent.Asia, flagEmoji: "🇮🇩" },
  { id: "iran", name: "Iran", code: "IRN", continent: Continent.Asia, flagEmoji: "🇮🇷" },
  { id: "iraq", name: "Iraq", code: "IRQ", continent: Continent.Asia, flagEmoji: "🇮🇶" },
  { id: "israel", name: "Israel", code: "ISR", continent: Continent.Asia, flagEmoji: "🇮🇱" },
  { id: "japan", name: "Japan", code: "JPN", continent: Continent.Asia, flagEmoji: "🇯🇵" },
  { id: "jordan", name: "Jordan", code: "JOR", continent: Continent.Asia, flagEmoji: "🇯🇴" },
  { id: "kazakhstan", name: "Kazakhstan", code: "KAZ", continent: Continent.Asia, flagEmoji: "🇰🇿" },
  { id: "kuwait", name: "Kuwait", code: "KWT", continent: Continent.Asia, flagEmoji: "🇰🇼" },
  { id: "kyrgyzstan", name: "Kyrgyzstan", code: "KGZ", continent: Continent.Asia, flagEmoji: "🇰🇬" },
  { id: "laos", name: "Laos", code: "LAO", continent: Continent.Asia, flagEmoji: "🇱🇦" },
  { id: "lebanon", name: "Lebanon", code: "LBN", continent: Continent.Asia, flagEmoji: "🇱🇧" },
  { id: "malaysia", name: "Malaysia", code: "MYS", continent: Continent.Asia, flagEmoji: "🇲🇾" },
  { id: "maldives", name: "Maldives", code: "MDV", continent: Continent.Asia, flagEmoji: "🇲🇻" },
  { id: "mongolia", name: "Mongolia", code: "MNG", continent: Continent.Asia, flagEmoji: "🇲🇳" },
  { id: "myanmar", name: "Myanmar", code: "MMR", continent: Continent.Asia, flagEmoji: "🇲🇲" },
  { id: "nepal", name: "Nepal", code: "NPL", continent: Continent.Asia, flagEmoji: "🇳🇵" },
  { id: "north-korea", name: "North Korea", code: "PRK", continent: Continent.Asia, flagEmoji: "🇰🇵" },
  { id: "oman", name: "Oman", code: "OMN", continent: Continent.Asia, flagEmoji: "🇴🇲" },
  { id: "pakistan", name: "Pakistan", code: "PAK", continent: Continent.Asia, flagEmoji: "🇵🇰" },
  { id: "philippines", name: "Philippines", code: "PHL", continent: Continent.Asia, flagEmoji: "🇵🇭" },
  { id: "qatar", name: "Qatar", code: "QAT", continent: Continent.Asia, flagEmoji: "🇶🇦" },
  { id: "saudi-arabia", name: "Saudi Arabia", code: "SAU", continent: Continent.Asia, flagEmoji: "🇸🇦" },
  { id: "singapore", name: "Singapore", code: "SGP", continent: Continent.Asia, flagEmoji: "🇸🇬" },
  { id: "south-korea", name: "South Korea", code: "KOR", continent: Continent.Asia, flagEmoji: "🇰🇷" },
  { id: "sri-lanka", name: "Sri Lanka", code: "LKA", continent: Continent.Asia, flagEmoji: "🇱🇰" },
  { id: "syria", name: "Syria", code: "SYR", continent: Continent.Asia, flagEmoji: "🇸🇾" },
  { id: "tajikistan", name: "Tajikistan", code: "TJK", continent: Continent.Asia, flagEmoji: "🇹🇯" },
  { id: "thailand", name: "Thailand", code: "THA", continent: Continent.Asia, flagEmoji: "🇹🇭" },
  { id: "timor-leste", name: "Timor-Leste", code: "TLS", continent: Continent.Asia, flagEmoji: "🇹🇱" },
  { id: "turkey", name: "Turkey", code: "TUR", continent: Continent.Asia, flagEmoji: "🇹🇷" },
  { id: "turkmenistan", name: "Turkmenistan", code: "TKM", continent: Continent.Asia, flagEmoji: "🇹🇲" },
  { id: "uae", name: "United Arab Emirates", code: "ARE", continent: Continent.Asia, flagEmoji: "🇦🇪" },
  { id: "uzbekistan", name: "Uzbekistan", code: "UZB", continent: Continent.Asia, flagEmoji: "🇺🇿" },
  { id: "vietnam", name: "Vietnam", code: "VNM", continent: Continent.Asia, flagEmoji: "🇻🇳" },
  { id: "yemen", name: "Yemen", code: "YEM", continent: Continent.Asia, flagEmoji: "🇾🇪" },
  
  // Europe (43 countries)
  { id: "albania", name: "Albania", code: "ALB", continent: Continent.Europe, flagEmoji: "🇦🇱" },
  { id: "andorra", name: "Andorra", code: "AND", continent: Continent.Europe, flagEmoji: "🇦🇩" },
  { id: "austria", name: "Austria", code: "AUT", continent: Continent.Europe, flagEmoji: "🇦🇹" },
  { id: "belarus", name: "Belarus", code: "BLR", continent: Continent.Europe, flagEmoji: "🇧🇾" },
  { id: "belgium", name: "Belgium", code: "BEL", continent: Continent.Europe, flagEmoji: "🇧🇪" },
  { id: "bosnia-herzegovina", name: "Bosnia and Herzegovina", code: "BIH", continent: Continent.Europe, flagEmoji: "🇧🇦" },
  { id: "bulgaria", name: "Bulgaria", code: "BGR", continent: Continent.Europe, flagEmoji: "🇧🇬" },
  { id: "croatia", name: "Croatia", code: "HRV", continent: Continent.Europe, flagEmoji: "🇭🇷" },
  { id: "czech-republic", name: "Czech Republic", code: "CZE", continent: Continent.Europe, flagEmoji: "🇨🇿" },
  { id: "denmark", name: "Denmark", code: "DNK", continent: Continent.Europe, flagEmoji: "🇩🇰" },
  { id: "estonia", name: "Estonia", code: "EST", continent: Continent.Europe, flagEmoji: "🇪🇪" },
  { id: "finland", name: "Finland", code: "FIN", continent: Continent.Europe, flagEmoji: "🇫🇮" },
  { id: "france", name: "France", code: "FRA", continent: Continent.Europe, flagEmoji: "🇫🇷" },
  { id: "germany", name: "Germany", code: "DEU", continent: Continent.Europe, flagEmoji: "🇩🇪" },
  { id: "greece", name: "Greece", code: "GRC", continent: Continent.Europe, flagEmoji: "🇬🇷" },
  { id: "hungary", name: "Hungary", code: "HUN", continent: Continent.Europe, flagEmoji: "🇭🇺" },
  { id: "iceland", name: "Iceland", code: "ISL", continent: Continent.Europe, flagEmoji: "🇮🇸" },
  { id: "ireland", name: "Ireland", code: "IRL", continent: Continent.Europe, flagEmoji: "🇮🇪" },
  { id: "italy", name: "Italy", code: "ITA", continent: Continent.Europe, flagEmoji: "🇮🇹" },
  { id: "latvia", name: "Latvia", code: "LVA", continent: Continent.Europe, flagEmoji: "🇱🇻" },
  { id: "liechtenstein", name: "Liechtenstein", code: "LIE", continent: Continent.Europe, flagEmoji: "🇱🇮" },
  { id: "lithuania", name: "Lithuania", code: "LTU", continent: Continent.Europe, flagEmoji: "🇱🇹" },
  { id: "luxembourg", name: "Luxembourg", code: "LUX", continent: Continent.Europe, flagEmoji: "🇱🇺" },
  { id: "malta", name: "Malta", code: "MLT", continent: Continent.Europe, flagEmoji: "🇲🇹" },
  { id: "moldova", name: "Moldova", code: "MDA", continent: Continent.Europe, flagEmoji: "🇲🇩" },
  { id: "monaco", name: "Monaco", code: "MCO", continent: Continent.Europe, flagEmoji: "🇲🇨" },
  { id: "montenegro", name: "Montenegro", code: "MNE", continent: Continent.Europe, flagEmoji: "🇲🇪" },
  { id: "netherlands", name: "Netherlands", code: "NLD", continent: Continent.Europe, flagEmoji: "🇳🇱" },
  { id: "north-macedonia", name: "North Macedonia", code: "MKD", continent: Continent.Europe, flagEmoji: "🇲🇰" },
  { id: "norway", name: "Norway", code: "NOR", continent: Continent.Europe, flagEmoji: "🇳🇴" },
  { id: "poland", name: "Poland", code: "POL", continent: Continent.Europe, flagEmoji: "🇵🇱" },
  { id: "portugal", name: "Portugal", code: "PRT", continent: Continent.Europe, flagEmoji: "🇵🇹" },
  { id: "romania", name: "Romania", code: "ROU", continent: Continent.Europe, flagEmoji: "🇷🇴" },
  { id: "russia", name: "Russia", code: "RUS", continent: Continent.Europe, flagEmoji: "🇷🇺" },
  { id: "san-marino", name: "San Marino", code: "SMR", continent: Continent.Europe, flagEmoji: "🇸🇲" },
  { id: "serbia", name: "Serbia", code: "SRB", continent: Continent.Europe, flagEmoji: "🇷🇸" },
  { id: "slovakia", name: "Slovakia", code: "SVK", continent: Continent.Europe, flagEmoji: "🇸🇰" },
  { id: "slovenia", name: "Slovenia", code: "SVN", continent: Continent.Europe, flagEmoji: "🇸🇮" },
  { id: "spain", name: "Spain", code: "ESP", continent: Continent.Europe, flagEmoji: "🇪🇸" },
  { id: "sweden", name: "Sweden", code: "SWE", continent: Continent.Europe, flagEmoji: "🇸🇪" },
  { id: "switzerland", name: "Switzerland", code: "CHE", continent: Continent.Europe, flagEmoji: "🇨🇭" },
  { id: "ukraine", name: "Ukraine", code: "UKR", continent: Continent.Europe, flagEmoji: "🇺🇦" },
  { id: "united-kingdom", name: "United Kingdom", code: "GBR", continent: Continent.Europe, flagEmoji: "🇬🇧" },
  
  // North America (23 countries)
  { id: "antigua-and-barbuda", name: "Antigua and Barbuda", code: "ATG", continent: Continent.NorthAmerica, flagEmoji: "🇦🇬" },
  { id: "bahamas", name: "Bahamas", code: "BHS", continent: Continent.NorthAmerica, flagEmoji: "🇧🇸" },
  { id: "barbados", name: "Barbados", code: "BRB", continent: Continent.NorthAmerica, flagEmoji: "🇧🇧" },
  { id: "belize", name: "Belize", code: "BLZ", continent: Continent.NorthAmerica, flagEmoji: "🇧🇿" },
  { id: "canada", name: "Canada", code: "CAN", continent: Continent.NorthAmerica, flagEmoji: "🇨🇦" },
  { id: "costa-rica", name: "Costa Rica", code: "CRI", continent: Continent.NorthAmerica, flagEmoji: "🇨🇷" },
  { id: "cuba", name: "Cuba", code: "CUB", continent: Continent.NorthAmerica, flagEmoji: "🇨🇺" },
  { id: "dominica", name: "Dominica", code: "DMA", continent: Continent.NorthAmerica, flagEmoji: "🇩🇲" },
  { id: "dominican-republic", name: "Dominican Republic", code: "DOM", continent: Continent.NorthAmerica, flagEmoji: "🇩🇴" },
  { id: "el-salvador", name: "El Salvador", code: "SLV", continent: Continent.NorthAmerica, flagEmoji: "🇸🇻" },
  { id: "grenada", name: "Grenada", code: "GRD", continent: Continent.NorthAmerica, flagEmoji: "🇬🇩" },
  { id: "guatemala", name: "Guatemala", code: "GTM", continent: Continent.NorthAmerica, flagEmoji: "🇬🇹" },
  { id: "haiti", name: "Haiti", code: "HTI", continent: Continent.NorthAmerica, flagEmoji: "🇭🇹" },
  { id: "honduras", name: "Honduras", code: "HND", continent: Continent.NorthAmerica, flagEmoji: "🇭🇳" },
  { id: "jamaica", name: "Jamaica", code: "JAM", continent: Continent.NorthAmerica, flagEmoji: "🇯🇲" },
  { id: "mexico", name: "Mexico", code: "MEX", continent: Continent.NorthAmerica, flagEmoji: "🇲🇽" },
  { id: "nicaragua", name: "Nicaragua", code: "NIC", continent: Continent.NorthAmerica, flagEmoji: "🇳🇮" },
  { id: "panama", name: "Panama", code: "PAN", continent: Continent.NorthAmerica, flagEmoji: "🇵🇦" },
  { id: "saint-kitts-and-nevis", name: "Saint Kitts and Nevis", code: "KNA", continent: Continent.NorthAmerica, flagEmoji: "🇰🇳" },
  { id: "saint-lucia", name: "Saint Lucia", code: "LCA", continent: Continent.NorthAmerica, flagEmoji: "🇱🇨" },
  { id: "saint-vincent-grenadines", name: "Saint Vincent and the Grenadines", code: "VCT", continent: Continent.NorthAmerica, flagEmoji: "🇻🇨" },
  { id: "trinidad-and-tobago", name: "Trinidad and Tobago", code: "TTO", continent: Continent.NorthAmerica, flagEmoji: "🇹🇹" },
  { id: "united-states", name: "United States", code: "USA", continent: Continent.NorthAmerica, flagEmoji: "🇺🇸" },
  
  // South America (12 countries)
  { id: "argentina", name: "Argentina", code: "ARG", continent: Continent.SouthAmerica, flagEmoji: "🇦🇷" },
  { id: "bolivia", name: "Bolivia", code: "BOL", continent: Continent.SouthAmerica, flagEmoji: "🇧🇴" },
  { id: "brazil", name: "Brazil", code: "BRA", continent: Continent.SouthAmerica, flagEmoji: "🇧🇷" },
  { id: "chile", name: "Chile", code: "CHL", continent: Continent.SouthAmerica, flagEmoji: "🇨🇱" },
  { id: "colombia", name: "Colombia", code: "COL", continent: Continent.SouthAmerica, flagEmoji: "🇨🇴" },
  { id: "ecuador", name: "Ecuador", code: "ECU", continent: Continent.SouthAmerica, flagEmoji: "🇪🇨" },
  { id: "guyana", name: "Guyana", code: "GUY", continent: Continent.SouthAmerica, flagEmoji: "🇬🇾" },
  { id: "paraguay", name: "Paraguay", code: "PRY", continent: Continent.SouthAmerica, flagEmoji: "🇵🇾" },
  { id: "peru", name: "Peru", code: "PER", continent: Continent.SouthAmerica, flagEmoji: "🇵🇪" },
  { id: "suriname", name: "Suriname", code: "SUR", continent: Continent.SouthAmerica, flagEmoji: "🇸🇷" },
  { id: "uruguay", name: "Uruguay", code: "URY", continent: Continent.SouthAmerica, flagEmoji: "🇺🇾" },
  { id: "venezuela", name: "Venezuela", code: "VEN", continent: Continent.SouthAmerica, flagEmoji: "🇻🇪" },
  
  // Oceania (14 countries)
  { id: "australia", name: "Australia", code: "AUS", continent: Continent.Oceania, flagEmoji: "🇦🇺" },
  { id: "fiji", name: "Fiji", code: "FJI", continent: Continent.Oceania, flagEmoji: "🇫🇯" },
  { id: "kiribati", name: "Kiribati", code: "KIR", continent: Continent.Oceania, flagEmoji: "🇰🇮" },
  { id: "marshall-islands", name: "Marshall Islands", code: "MHL", continent: Continent.Oceania, flagEmoji: "🇲🇭" },
  { id: "micronesia", name: "Micronesia", code: "FSM", continent: Continent.Oceania, flagEmoji: "🇫🇲" },
  { id: "nauru", name: "Nauru", code: "NRU", continent: Continent.Oceania, flagEmoji: "🇳🇷" },
  { id: "new-zealand", name: "New Zealand", code: "NZL", continent: Continent.Oceania, flagEmoji: "🇳🇿" },
  { id: "palau", name: "Palau", code: "PLW", continent: Continent.Oceania, flagEmoji: "🇵🇼" },
  { id: "papua-new-guinea", name: "Papua New Guinea", code: "PNG", continent: Continent.Oceania, flagEmoji: "🇵🇬" },
  { id: "samoa", name: "Samoa", code: "WSM", continent: Continent.Oceania, flagEmoji: "🇼🇸" },
  { id: "solomon-islands", name: "Solomon Islands", code: "SLB", continent: Continent.Oceania, flagEmoji: "🇸🇧" },
  { id: "tonga", name: "Tonga", code: "TON", continent: Continent.Oceania, flagEmoji: "🇹🇴" },
  { id: "tuvalu", name: "Tuvalu", code: "TUV", continent: Continent.Oceania, flagEmoji: "🇹🇻" },
  { id: "vanuatu", name: "Vanuatu", code: "VUT", continent: Continent.Oceania, flagEmoji: "🇻🇺" },
];

